services:
  db:
    image: postgres:17.5-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: homeshop
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
