name: Automated tests

on:
  pull_request:
    branches: [main]

jobs:
  vitest:
    name: Run Vitest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '23'
      - run: npm ci
      - run: npm test
